# Generated by Django 2.0.1 on 2018-01-21 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newstories', '0002_auto_20180121_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newstories',
            name='text',
        ),
    ]
