# Generated by Django 2.0.1 on 2018-01-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newstories', '0003_remove_newstories_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstories',
            name='text',
            field=models.TextField(default='default'),
        ),
    ]
