# Generated by Django 2.0.1 on 2018-01-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showstories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showstories',
            name='text',
            field=models.CharField(max_length=1000),
        ),
    ]
