# Generated by Django 2.0.1 on 2018-01-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobstories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('descendants', models.CharField(max_length=200)),
                ('story_id', models.CharField(max_length=200)),
                ('kids', models.CharField(max_length=500)),
                ('score', models.IntegerField(default=0)),
                ('text', models.CharField(max_length=500)),
                ('time', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
    ]
